language: java
dist: trusty
jdk: oraclejdk8
python:
  - "2.7"
env:
  - BAZEL_VERSION="0.3.0"
before_install:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install bazel
script:
  - bazel build kbir:kbir
  - bazel test tests:kbir_tests --test_arg "" --verbose_failures
branches:
  only:
    - master
