py_binary(
    name = "kbir",
    srcs = ["kbirparse.py"],
    deps = [
        ":kbirlib",
    ],
    main = "kbirparse.py",
)

py_library(
    name = "kbirlib",
    srcs = ["kbirlib.py"],
)

#py_test(
#    name = "runtests",
#    srcs = ["//tests:test_build"],
#)
